### ISSUE TITLE
Crash on start up with this mod 1.12.2

### ISSUE THREAD

**Issue by Caradogg** [Mrthomas20121/TinkerFirmaCraft#31]
**Describe the bug/crashreport**

 Failing to load when adding this to an otherwise functioning instance. Tried various versions weirdly get a crash that tells me TFCompat causes issues (even though it was fine without tinkers tfc in there) when using fully updated versions. Rolling back a bit it seems to run through more loading before telling me this mod makes an issue.

Im probably being dense and missing something obvious but Im lost, Im sure I have all required mods, its weird that your mod seems to be causing issues with your own mods...can't say I've seen that before. But something not happy with rocksalt/biolib/tfcompat/tfc tinkers.
**To Reproduce**
Steps to reproduce the bug/crash.

**Expected behavior**
What should happen.

**Screenshots**

**Crash report Link**
java.lang.NoClassDefFoundError: mrthomas20121/biolib/library/SmelteryUtils
    at mrthomas20121.tfc_tinker.registry.RegistryHandler.onRecipeEvent(RegistryHandler.java:151)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_767_RegistryHandler_onRecipeEvent_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ClassNotFoundException: mrthomas20121.biolib.library.SmelteryUtils
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 26 more
Caused by: java.lang.NullPointerException
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 28 more

**Version**
 - Minecraft: :
 - TFC Tinkers :
 - Forge :

**Additional mods involved**
Add any other mods about the problem here(mod:version).

**Comment by Mrthomas20121** [comment]
downgrade biolib.
