### ISSUE TITLE
A error

### ISSUE THREAD

**Issue by zjz-Beiming** [Mrthomas20121/TinkerFirmaCraft#32]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  GregTechLoadingPlugin ([科技-GTCEu]gregtech-1.12.2-2.3.4-beta.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([辅助-泡沫修复]foamfix-0.10.14-1.12.2.jar)
  Inventory Tweaks Coremod ([辅助-R键整理]InventoryTweaks-1.63.jar)
  CTMCorePlugin ([辅助-连接纹理]CTM-MC1.12.2-1.0.2.31.jar)
  MekanismCoremod ([科技-通用机械]Mekanism-1.12.2-9.8.3.390.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 8/15/22 4:18 PM
Description: Initializing game

java.lang.NoClassDefFoundError: mrthomas20121/rocksalt/utils/MetalUtils
	at mrthomas20121.tfc_tinker.objects.items.TFCTinkerItems.init(TFCTinkerItems.java:37)
	at mrthomas20121.tfc_tinker.CommonProxy.registerItems(CommonProxy.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_439_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mrthomas20121.rocksalt.utils.MetalUtils
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 18 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mrthomas20121.tfc_tinker.objects.items.TFCTinkerItems.init(TFCTinkerItems.java:37)
	at mrthomas20121.tfc_tinker.CommonProxy.registerItems(CommonProxy.java:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_439_CommonProxy_registerItems_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:850)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_345, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 7733888816 bytes (7375 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 12 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16m -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:-DontCompileHugeMethods -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 45 mods loaded, 45 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                                         | Signature                                |
	|:----- |:-------------------- |:------------------------ |:-------------------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                                  | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                                  | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2860             | forge-1.12.2-14.23.5.2860.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                                  | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2445               | [世界-BOP]BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar          | None                                     |
	| LCH   | ctm                  | MC1.12.2-1.0.2.31        | [辅助-连接纹理]CTM-MC1.12.2-1.0.2.31.jar                             | None                                     |
	| LCH   | twilightforest       | 3.11.1021                | [世界-暮色森林]twilightforest-1.12.2-3.11.1021-universal.jar         | None                                     |
	| LCH   | waila                | 1.8.26                   | [辅助-Hwyla]Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCH   | jei                  | 4.16.1.302               | [辅助-JEI]jei_1.12.2-4.16.1.302.jar                              | None                                     |
	| LCH   | tfc                  | 1.7.23.181               | [冒险-群峦传说]TerraFirmaCraft-MC1.12.2-1.7.23.181.jar               | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.55            | [前置-地幔]Mantle-1.12-1.3.3.55.jar                                | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.13.0.183        | [科技-匠魂]TConstruct-1.12.2-2.13.0.183.jar                        | None                                     |
	| LCH   | biolib               | 1.1.3                    | [前置-BioLib]biolib-1.1.3.jar                                    | None                                     |
	| LCH   | codechickenlib       | 3.2.3.358                | [前置-CCL]CodeChickenLib-1.12.2-3.2.3.358-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | ftblib               | 5.4.7.2                  | [前置-FTBL]FTBLib-5.4.7.2.jar                                    | None                                     |
	| LCH   | lunatriuscore        | 1.2.0.42                 | [前置-LunatriusCore]LunatriusCore-1.12.2-1.2.0.42-universal.jar  | None                                     |
	| LCH   | mcmultipart          | 2.5.3                    | [前置-MCMP]MCMultiPart-2.5.3.jar                                 | None                                     |
	| LCH   | rocksalt             | 1.0.4                    | [前置-Rocksalt]rocksalt-1.0.4.jar                                | None                                     |
	| LCH   | itemfilters          | 1.0.4.2                  | [前置-物品过滤器]ItemFilters-1.0.4.2.jar                              | None                                     |
	| LCH   | appliedenergistics2  | rv6-stable-7             | [科技-AE2]appliedenergistics2-rv6-stable-7.jar                   | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | gregtech             | 2.3.4-beta               | [科技-GTCEu]gregtech-1.12.2-2.3.4-beta.jar                       | None                                     |
	| LCH   | gcym                 | 1.1.2                    | [科技-GCYM]GregicalityMultiblocks-1.12.2-1.1.2.jar               | None                                     |
	| LCH   | ic2                  | 2.8.222-ex112            | [科技-IC2]industrialcraft-2-2.8.222-ex112.jar                    | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | mechtech             | 1.1.0-beta               | [科技-机械工程]mechtech-1.1.0-beta.jar                               | None                                     |
	| LCH   | gregtechfoodoption   | 1.12.2-1.6.3             | [科技-格雷科技食物优选]GregTech+Food+Option-1.12.2-1.6.3.jar             | None                                     |
	| LCH   | immersiveengineering | 0.12-98                  | [科技-沉浸工程]ImmersiveEngineering-0.12-98.jar                      | None                                     |
	| LCH   | immersivepetroleum   | 1.1.10                   | [科技-沉浸原油]immersivepetroleum-1.12.2-1.1.10.jar                  | None                                     |
	| LCH   | tfctreatedwood       | 1.0.0                    | [科技-群峦·防腐木]TFC-TreatedWood-1.12.2-1.0.0.jar                    | None                                     |
	| LCH   | tfcmetallum          | 1.4.2                    | [科技-群峦合金]TFC-Metallum-MC1.12.2-1.4.2.jar                       | None                                     |
	| LCH   | tfctech              | 1.2.16                   | [科技-群峦工业非官方版]TFCTech-Unofficial-MC1.12.2-1.2.16.jar            | None                                     |
	| LCH   | att                  | 0.2.3                    | [科技-进阶群峦科技]AdvancedTFCTech-0.2.3.jar                           | None                                     |
	| LCH   | mekanism             | 1.12.2-9.8.3.390         | [科技-通用机械]Mekanism-1.12.2-9.8.3.390.jar                         | None                                     |
	| LCH   | ftbquests            | 1202.9.0.15              | [辅助-FTBQ]FTBQuests-1202.9.0.15.jar                             | None                                     |
	| LCH   | ingameinfoxml        | 2.8.2.94                 | [辅助-IGI]InGameInfoXML-1.12.2-2.8.2.94-universal.jar            | None                                     |
	| LCH   | jeiintegration       | 1.6.0                    | [辅助-JEI拓展]jeiintegration_1.12.2-1.6.0.jar                      | None                                     |
	| LCH   | justenoughpetroleum  | 0.1                      | [辅助-JEP]JustEnoughPetroleum-0.1.jar                            | None                                     |
	| LCH   | nei                  | 2.4.3                    | [辅助-NEI]NotEnoughItems-1.12.2-2.4.3.245-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | inventorytweaks      | 1.63+release.109.220f184 | [辅助-R键整理]InventoryTweaks-1.63.jar                              | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LCH   | wailaharvestability  | 1.1.12                   | [辅助-Waila Harvestability]WailaHarvestability-mc1.12-1.1.12.jar | None                                     |
	| LCH   | wawla                | 2.6.275                  | [辅助-Wawla]Wawla-1.12.2-2.6.275.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | journeymap           | 1.12.2-5.7.1             | [辅助-旅行地图]journeymap-1.12.2-5.7.1.jar                           | None                                     |
	| LCH   | foamfix              | 0.10.14-1.12.2           | [辅助-泡沫修复]foamfix-0.10.14-1.12.2.jar                            | None                                     |
	| LCH   | i18nmod              | 1.12.2-1.1.0             | [辅助-自动汉化更新]i18nupdatemod-1.12.2-1.1.0.jar                      | None                                     |
	| LCH   | tfc_tinker           | 1.5.6                    | tfc_tinkers-1.5.6.jar                                          | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
GregTechLoadingPlugin ([科技-GTCEu]gregtech-1.12.2-2.3.4-beta.jar)
  gregtech.core.GregTechTransformer
Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) ([辅助-泡沫修复]foamfix-0.10.14-1.12.2.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
Inventory Tweaks Coremod ([辅助-R键整理]InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
CTMCorePlugin ([辅助-连接纹理]CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MekanismCoremod ([科技-通用机械]Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.69' Renderer: 'NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 GL version 4.6.0 NVIDIA 511.69, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Minecraft-Mod-Language-Modpack.zip
	Current Language: 简体中文 (中国)
	Profiler Position: N/A (disabled)
	CPU: 16x 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

**Comment by ACGaming** [comment]
Update TFC Tinkers to version 1.5.7.

**Comment by zjz-Beiming** [comment]
> Update TFC Tinkers to version 1.5.7.

1.5.7 have same problem

**Comment by ACGaming** [comment]
Then try this mod set:
* biolib-1.1.2
* rocksalt-1.0.3
* tfc_tinkers-1.5.6
